-- MySQL Script generated by MySQL Workbench
-- Tue Aug 20 12:21:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbfaktor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbfaktor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfaktor` DEFAULT CHARACTER SET utf8 ;
USE `dbfaktor` ;

-- -----------------------------------------------------
-- Table `dbfaktor`.`DocumentosPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfaktor`.`DocumentosPersonal` (
  `idDocumentosPersonal` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(200) NULL,
  `cedulaBancaria` VARCHAR(200) NULL,
  `cedulaFiscal` VARCHAR(200) NULL,
  `fechaCreacion` DATETIME NULL,
  `fechaFinal` DATETIME NULL,
  PRIMARY KEY (`idDocumentosPersonal`))
ENGINE = InnoDB;

INSERT INTO `DocumentosPersonal` (`idDocumentosPersonal`, `identificacion`, `cedulaBancaria`, `cedulaFiscal`, `fechaCreacion`, `fechaFinal`) VALUES
('Master@gmail.com', 'Sin ruta', 'Sin ruta', 'Sin ruta', '2000-01-01 00:00:00','2000-01-01 00:00:00');
-- -----------------------------------------------------
-- Table `dbfaktor`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfaktor`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `passwordUsuario` VARCHAR(45) NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `apellidoPatUsuario` VARCHAR(45) NULL,
  `apellidoMatUsuario` VARCHAR(45) NULL,
  `direccionUsuario` VARCHAR(45) NULL,
  `numTelefonoUsuario` VARCHAR(45) NULL,
  `numCuenta` VARCHAR(45) NULL,
  `bancoAfiliado` VARCHAR(45) NULL,
  `folioFiscal` VARCHAR(45) NULL,
  `rfc` VARCHAR(45) NULL,
  `isDeleted` TINYINT NULL,
  `status` VARCHAR(45) NULL,
  `infoCompleta` INT NULL,
  `fechaCreacionUser` DATETIME NULL,
  `rolUsuario` VARCHAR(45) NULL,
  `DocumentosPersonal_idDocumentosPersonal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_DocumentosPersonal1_idx` (`DocumentosPersonal_idDocumentosPersonal` ASC),
  CONSTRAINT `fk_Usuario_DocumentosPersonal1`
    FOREIGN KEY (`DocumentosPersonal_idDocumentosPersonal`)
    REFERENCES `dbfaktor`.`DocumentosPersonal` (`idDocumentosPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `Usuario` (`idUsuario`, `usuario`, `nombreUsuario`, `passwordUsuario`, `rolUsuario`, `DocumentosPersonal_idDocumentosPersonal`) VALUES
('1', 'Master@gmail.com', 'Master','202cb962ac59075b964b07152d234b70', '1','Master@gmail.com');

-- -----------------------------------------------------
-- Table `dbfaktor`.`documentosCasoMedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfaktor`.`documentosCasoMedico` (
  `iddocumentosCasoMedico` INT NOT NULL AUTO_INCREMENT,
  `pdfCartaAprobacion` VARCHAR(45) NULL,
  `pdfFacturaHonorarios` VARCHAR(45) NULL,
  `xmlFacturaHonorarios` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`iddocumentosCasoMedico`),
  INDEX `fk_documentosCasoMedico_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_documentosCasoMedico_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `dbfaktor`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfaktor`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfaktor`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `nombrePaciente` VARCHAR(45) NULL,
  `apellidoPatPaciente` VARCHAR(45) NULL,
  `apellidoMatPaciente` VARCHAR(45) NULL,
  `hospital` VARCHAR(45) NULL,
  `cuartoHospital` VARCHAR(45) NULL,
  `numTelefonoPaciente` VARCHAR(45) NULL,
  `emailPaciente` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPaciente`, `Usuario_idUsuario`),
  INDEX `fk_Paciente_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Paciente_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `dbfaktor`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfaktor`.`Aseguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfaktor`.`Aseguradora` (
  `idAseguradora` INT NOT NULL AUTO_INCREMENT,
  `nombreAseguradra` VARCHAR(45) NULL,
  `direccionAseguradora` VARCHAR(45) NULL,
  `pagina` VARCHAR(45) NULL,
  PRIMARY KEY (`idAseguradora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfaktor`.`CasoMedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfaktor`.`CasoMedico` (
  `idCasoMedico` INT NOT NULL AUTO_INCREMENT,
  `siniestro` VARCHAR(45) NULL,
  `fechaCasoMedico` DATETIME NULL,
  `descripcion` VARCHAR(100) NULL,
  `rolMedicoEnCaso` VARCHAR(45) NULL,
  `honorariosMedico` DOUBLE NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `documentosCasoMedico_iddocumentosCasoMedico` INT NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Aseguradora_idAseguradora` INT NOT NULL,
  PRIMARY KEY (`idCasoMedico`, `documentosCasoMedico_iddocumentosCasoMedico`),
  INDEX `fk_CasoMedico_Usuario_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_CasoMedico_documentosCasoMedico1_idx` (`documentosCasoMedico_iddocumentosCasoMedico` ASC),
  INDEX `fk_CasoMedico_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_CasoMedico_Aseguradora1_idx` (`Aseguradora_idAseguradora` ASC),
  CONSTRAINT `fk_CasoMedico_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `dbfaktor`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CasoMedico_documentosCasoMedico1`
    FOREIGN KEY (`documentosCasoMedico_iddocumentosCasoMedico`)
    REFERENCES `dbfaktor`.`documentosCasoMedico` (`iddocumentosCasoMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CasoMedico_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `dbfaktor`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CasoMedico_Aseguradora1`
    FOREIGN KEY (`Aseguradora_idAseguradora`)
    REFERENCES `dbfaktor`.`Aseguradora` (`idAseguradora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbfaktor`.`Usuario_has_Aseguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfaktor`.`Usuario_has_Aseguradora` (
  `Usuario_idUsuario` INT NOT NULL,
  `Aseguradora_idAseguradora` INT NOT NULL,
  `usuarioAseguradora` VARCHAR(45) NULL,
  `passwodAseguradora` VARCHAR(45) NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Aseguradora_idAseguradora`),
  INDEX `fk_Usuario_has_Aseguradora_Aseguradora1_idx` (`Aseguradora_idAseguradora` ASC),
  INDEX `fk_Usuario_has_Aseguradora_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Aseguradora_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `dbfaktor`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Aseguradora_Aseguradora1`
    FOREIGN KEY (`Aseguradora_idAseguradora`)
    REFERENCES `dbfaktor`.`Aseguradora` (`idAseguradora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
